export const scenes=[
 {title:'One cell. Two explanations.',tag:'01 / THE MYSTERY',duration:10,beats:[['The same abnormal battery response can have more than one internal explanation.','Hypothesis ambiguity'],['Battery MRI designs the electrical question that makes competing explanations easier to distinguish.','Active experiment design']]},
 {title:'An ordinary test leaves ambiguity.',tag:'02 / THE CONTROL',duration:11,beats:[['PyBaMM is an open-source battery-physics simulator. It predicts both virtual cells under the same current pattern.','PyBaMM · SPMe physics simulation'],['SPMe is a reduced electrochemical model: fast enough for repeated search, with physically meaningful battery dynamics.','The fixed baseline probe has little expected information']]},
 {title:'Choose a better question.',tag:'03 / PROBE DESIGN',duration:13,beats:[['A probe is a timed pattern of charge, discharge and rest. The optimizer searches bounded patterns in the physics model.','SciPy · bounded waveform optimization'],['Expected information gain measures how much a future measurement should reduce uncertainty. Here it is computed in bits.','Replaying real precomputed optimization history'],['Keep the best tested waveform that satisfies the virtual operating bounds. A bounded search is not proof of a global optimum.','Best safe probe found in this search']]},
 {title:'Make the physics distinguishable.',tag:'04 / PREDICT THE RESPONSE',duration:10,beats:[['Both hypotheses receive exactly the same optimized input. Their predicted voltage trajectories separate.','PyBaMM predicts the virtual response to a proposed current input'],['The highlighted point has the largest predicted voltage difference. This is a diagnostic part of this simulated response.','Model predictions · not laboratory measurements']]},
 {title:'Ask the mystery cell.',tag:'05 / SYNTHETIC MEASUREMENT',duration:13,beats:[['Apply the selected probe to the hidden virtual cell. Add the stated Gaussian voltage noise.','Observed synthetic measurement'],['Bayesian inference combines prior belief with how well each hypothesis predicts each arriving sample.','Likelihood → posterior probability'],['These confidence values come from numerical likelihoods, not from a scripted percentage or an LLM.','Posterior belief after measurement']]},
 {title:'Let the evidence guide the next test.',tag:'06 / CLOSE THE LOOP',duration:16,beats:[['The first posterior becomes the second search’s prior. Each probe assumes the cell is reconditioned to the same initial state.','Posterior₁ → Prior₂ · controlled reset assumption'],['The next search recomputes expected information using the updated belief. These two hypotheses can share the same global best waveform.','Use new evidence to redesign the next probe'],['A second independent synthetic measurement updates confidence again. More evidence can help, but no individual outcome is guaranteed.','Closed-loop experiment · second Bayesian update']]},
 {title:'From passive analysis to active interrogation.',tag:'07 / THE RESULT',duration:10,beats:[['Physics predicts responses. Optimization selects an experiment. Measurement updates belief. The loop can repeat.','Software-defined experiment'],['A real deployment needs cell-specific calibration, instrumentation error models, hardware integration and physical safety validation.','Simulation-based proof of concept · not a validated diagnostic']]}
];
export const glossary:Record<string,string>={
 'PyBaMM':'Open-source battery-physics simulator. We use its Chen2020 NMC/graphite parameter set.',
 'SPMe':'Single Particle Model with electrolyte: a reduced electrochemical lithium-ion model.',
 'C-rate':'Current relative to nominal capacity. For this 5 Ah virtual cell, 1C means 5 A. Positive current is discharge.',
 'SEI resistance':'The solid electrolyte interphase is an electrode-interface layer. Hypothesis A increases its resistivity in a constant-SEI model; no SEI growth or direct thickness measurement is claimed.',
 'Solid diffusion':'Lithium transport inside active-material particles. Hypothesis B reduces the negative-particle diffusion coefficient.',
 'Waveform optimization':'A bounded differential-evolution search over six current amplitudes. Each segment has equal duration.',
 'Expected information gain':'Expected reduction in binary Shannon entropy, in bits. Evaluated by 32-point Gaussian quadrature under an independent Gaussian voltage-noise model.',
 'Bayesian posterior':'Prior probability times the measurement likelihood, normalized using log-sum-exp. It is conditional on the two specified hypotheses and noise model.',
 'Measurement noise':'Independent zero-mean Gaussian voltage errors at two-second intervals. Real sensor drift and model discrepancy are not included.',
 'Closed-loop design':'Use the last posterior as the next experiment’s prior. In this restricted binary model, the globally best waveform need not change.'};
